name: test artifacts
on: push

jobs:
  build-artifacs:
    runs-on: ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: build artifacts
        run: |
          yarn
          yarn build
        env:
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5YTBGV3JiTy9lRDZVd3NkL0RoQ1htZmExNDd3RmJaNmRMT1ZGVjczWTBKZ0FBQkFBQUFBQUFBQUFBQUlBQUFBQWdMekUzVkE4K0tWQ1hjeGt1Vkx2QnRUR3pzQjVuV0ZpM2czWXNkRm9hVUxrVnB6TUN3K1NheHJMREhQbUVWVFZRK3NIL1VsMDBHNW5ET1EzQno0UStSb21nRW4vZlpTaXIwZFh5ZmRlL1lSN0dKcHdyOUVPclVvdzFhVkxDVnZrbHM2T1o4Tk1NWEU9Cg==

      - name: Pre-release (linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cd ./src-tauri/target/release/bundle/appimage/
          chmod a+x ./tauri-studio_*.AppImage
          zip -r tauri-studio-x86_64-linux-appimage.zip tauri-studio_*.AppImage
          cd ../deb
          zip -r tauri-studio-x86_64-linux-deb.zip tauri-studio_*.deb
      - name: Pre-release (mac)
        if: matrix.platform == 'macos-latest'
        run: |
          cd ./src-tauri/target/release/bundle/macos
          zip -r tauri-studio-x86_64-darwin.zip tauri-studio.app
      - name: Pre-release (windows)
        if: matrix.platform == 'windows-latest'
        run: |
          Compress-Archive -CompressionLevel Optimal -Force -Path src-tauri/target/release/bundle/msi/* -DestinationPath src-tauri/target/release/tauri-studio-x86_64-windows-msi.zip
      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: linux-artifacts-appimage
          path: ./src-tauri/target/release/bundle/appimage/tauri-studio-x86_64-linux-appimage.zip
      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: linux-artifacts-deb
          path: ./src-tauri/target/release/bundle/deb/tauri-studio-x86_64-linux-deb.zip
      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'windows-latest'
        with:
          name: windows-artifacts
          path: ./src-tauri/target/release/tauri-studio-x86_64-windows-msi.zip
      - uses: actions/upload-artifact@v2
        if: matrix.platform == 'macos-latest'
        with:
          name: macos-artifacts
          path: ./src-tauri/target/release/bundle/macos/tauri-studio-x86_64-darwin.zip
